# Generated by Django 5.0.6 on 2024-07-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_productos_imagen_productos_nombre_productos_precio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Pedido',
        ),
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
